load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "Raven",
    srcs = [
        "Engine.cpp",
        "Engine.hpp",
    ],
    deps = [
        "@SadaLogger",
    ],
    visibility = ["//visibility:public"],
)
